const exp_detail = [
  {
    id: 1,
    title: "Vagaro Technologies",
    location: "Ahemdabad, Gujrat",
    splz:" Vagaro Technologies is a leading software company providing the services of E-Commerce Development, Custom Web Development, Software Maintenance, Software Enhancement, Software Testing and various IT related supports and solution provider",
    // join: new Date("2020-01-27"),
    // end: new Date("2022-10-01"),
    year: 2024,
    percent: "Role: Software Engineer (ReactJS)",
    role: "Create the Front end UI",
  },
  {
    id: 2,
    title: "Gajra Gears Pvt. Ltd",
    location: "Dewas Madhya Pradesh",
    splz:
      "Gear Mfg CompanyGajra Gears is a gear manufacturing company which deals with manufacturing of Transmission parts. Serving to Replacement as well as O.E. market of leading Automobile and agricultural equipment’s producer such as GKN, Krone, TAFE, TMTL, Force Motors B.Auto, Ashok Leyland, TATA and many more.",
    join: new Date("2023-03-15"),
    end: null,
    year: 2023,
    percent: "Assistant Manager",
    role: "IT Problem Solving and Maintaining ",
  },
  {
    id: 1,
    title: "Techium Infotech ",
    location: "Pune, Maharashtra",
    splz:" Techium InfoTech is a leading software company providing the services of E-Commerce Development, Custom Web Development, Software Maintenance, Software Enhancement, Software Testing and various IT related supports and solution provider",
    // join: new Date("2020-01-27"),
    // end: new Date("2022-10-01"),
    year: 2020,
    percent: "Role: Front End Developer",
    role: "Create the Front end UI",
  },
  // {
  //   id: 3,
  //   title: "Gajra Gears Pvt. Ltd",
  //   location: "Dewas Madhya Pradesh",
  //   splz:
  //     "Gear Mfg CompanyGajra Gears is a gear manufacturing company which deals with manufacturing of Transmission parts. Serving to Replacement as well as O.E. market of leading Automobile and agricultural equipment’s producer such as GKN, Krone, TAFE, TMTL, Force Motors B.Auto, Ashok Leyland, TATA and many more.",
  //   join: new Date("2019-03-15"),
  //   end: new Date("2023-03-15"),
  //   percent: "Assistant Manager",
  //   role: "New Product Development & PPAP Documentaion",
  // },
  // {
  //   id: 4,
  //   title: "Volvo Eicher Commercial Vehicle",
  //   location: "Dewas Madhya Pradesh",
  //   splz:
  //     "VECV is a Joint Venture of Eicher motors and Volvo, in Dewas Plant Transmission as well as Differential Gear are manufactured for Eicher as well as for other O.E. customers such as Caterpillar, Mahindra Motors, Royal Enfield, GKN, Krone, TAFE, TMTL, etc.",
  //   join: new Date("2018-5-28"),
  //   end: new Date("2019-3-14"),
  //   percent: "Senior Engineer",
  //   role: "Senior Engineer",
  // },
  // {
  //   id: 5,
  //   title: "Gajra Differential Gears Pvt. Ltd",
  //   location: "Dewas Madhya Pradesh",
  //   splz: `It’s a gear manufacturing company with wide variety of Differential gears, serving to Replacement as well as O.E. market of leading automobile and agricultural equipment’s Producer Such as GKN, Krone, TAFE, TMTL, B.Auto, Ashok Leyland, TATA etc.`,
  //   join: new Date("2016-5-12"),
  //   end: new Date("2018-5-15"),
  //   percent: "Junior Engineer",
  //   role: "Junior Engieneer",
  // },
];

export default exp_detail;
