const exp_detail = [
  {
    id: 6,
    title: "Infosys India",
    location: "Indore, Madhya Pradesh",
    splz:"Infosys is a leading software company providing its servies over the globe to transform the digital revolution.",
    join: new Date("2025-01-30"),
    end: null,
    year: 2025,
    designation: "Senior Assosiate Consultant",
    role: "Create the Frontend UI & Logic",
  },
  {
    id: 5,
    title: "Vagaro Technologies",
    location: "Ahemdabad, Gujrat",
    splz:" Vagaro Technologies is a leading software company serving the saloon, health and fitness industry by providing the SAAS. The Product is helping the businesses to grow continously by serving the customers ",
    join: new Date("2024-08-01"),
    end: new Date("2025-01-03"),
    year: 2024,
    designation: "Software Engineer (ReactJS)",
    role: "Create the Frontend UI & Logic",
  },
  {
    id: 4,
    title: "Gajra Gears Pvt. Ltd",
    location: "Dewas Madhya Pradesh",
    splz:
      "Gear Mfg CompanyGajra Gears is a gear manufacturing company which deals with manufacturing of Transmission parts. Serving to Replacement as well as O.E. market of leading Automobile and agricultural equipment’s producer such as GKN, Krone, TAFE, TMTL, Force Motors B.Auto, Ashok Leyland, TATA and many more.",
    join: new Date("2024-04-18"),
    end: new Date("2024-06-30"),
    year: 2024,
    designation: "Zonal Sales Manger",
    role: "Sales Activity",
  },
  {
    id: 3,
    title: "Gajra Gears Pvt. Ltd",
    location: "Dewas Madhya Pradesh",
    splz:
      "Gear Mfg CompanyGajra Gears is a gear manufacturing company which deals with manufacturing of Transmission parts. Serving to Replacement as well as O.E. market of leading Automobile and agricultural equipment’s producer such as GKN, Krone, TAFE, TMTL, Force Motors B.Auto, Ashok Leyland, TATA and many more.",
    join: new Date("2019-03-15"),
    end: new Date("2023-03-17"),
    year: 2019,
    designation: "Assistant Manager",
    role: "New Product Development & PPAP Documentaion (IT)",
  },
  {
    id: 2,
    title: "Volvo Eicher Commercial Vehicle",
    location: "Dewas Madhya Pradesh",
    splz:
      "VECV is a Joint Venture of Eicher motors and Volvo, in Dewas Plant Transmission as well as Differential Gear are manufactured for Eicher as well as for other O.E. customers such as Caterpillar, Mahindra Motors, Royal Enfield, GKN, Krone, TAFE, TMTL, etc.",
    join: new Date("2018-5-28"),
    end: new Date("2019-3-14"),
    year: 2018,
    designation: "Senior Engineer",
    role: "Design and Develop Bought out",
  },
  {
    id: 1,
    title: "Gajra Differential Gears Pvt. Ltd",
    location: "Dewas Madhya Pradesh",
    splz: `It’s a gear manufacturing company with wide variety of Differential gears, serving to Replacement as well as O.E. market of leading automobile and agricultural equipment’s Producer Such as GKN, Krone, TAFE, TMTL, B.Auto, Ashok Leyland, TATA etc.`,
    join: new Date("2016-09-12"),
    end: new Date("2018-05-15"),
    year: 2016,
    designation: "Junior Engineer",
    role: "Look after the Design & Development of gear",
  },
];

export default exp_detail;
